class PITInternalError(Exception):
    """Internal error wrapper"""
    pass