class CRNWarningException(Exception):  # 堆垛机故障 不可重试
    pass
